### ISSUE TITLE
Images not uploading

### ISSUE THREAD

**Issue by colmoneill** [YunoHost-Apps/bludit_ynh#9] opened 2021-05-27 12:35 UTC
### Uploading images via the admin interface does not complete

Hi, thank you for making bludit accessible via YNH! The issue I'm having is that image upload do not complete. I'm able to explore my system, select a file, a progress bar loads from left to right, but the image does not appear in the form after that it just hangs. I don't see any particularly relevant error messages in the console.

![Screenshot from 2021-05-27 13-21-05](https://user-images.githubusercontent.com/2122318/119825333-bf8b3f80-beee-11eb-8624-3b3de3ce7466.png)

### Context

- Hardware:  Operating System: Linux 4.19.0-16-amd64 x86_64 CPU: Intel(R) Pentium(R) CPU G3250 @ 3.20GHz (2 cores) Memory: 7.73 GB
- YunoHost version:  **YunoHost 4.2.4 (stable)**
- I have access to my server: **Through SSH, through the webadmin and direct access via keyboard / screen**
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: **no**
- If yes, please explain:

### Steps to reproduce

- (following https://docs.bludit.com/en/content/how-to-upload-and-insert-an-image)
- click on 'images' button in article editor view
- select file from local FS to upload
- upload progress bar activates and completes
- the process finishes here

### Expected behavior

I expected the uploaded image to show in a preview as demonstrated in the general Bludit docs, instead, the form just seems to stop.

Tried uploading using a different browser (so I have now tested Firefox and Ungoogled-Chromium) and both produce the same issue.

### Logs

Installation of Bludit log (can't seem to find any other relevant logs?)

https://paste.yunohost.org/raw/wixomahido

Thank you very much!

Best regards,

**Comment by ericgaspar** [comment] 2021-05-27 15:35
I can't reproduce the issue on a fresh Bludit install...
- How big is your image?
- What format is it ? jepg,  PNG ... (have you tried different formats/image/sizes?)

**Comment by colmoneill** [comment] 2021-06-01 10:47
Thanks @ericgaspar 

My images were JPGs and relatively large, but below 2MB, (1.7 and 1.9 JPGs were some of the images I was trying to use).

Lighter PNGs work well, so I don't think the system is at fault here.

Would you know where I can change the allowed upload size?

Thanks for the fast reply,

Best regards,

**Comment by ericgaspar** [comment] 2021-06-01 13:01
Fixed with #11
Allowed upload size is increased to 10M instead of the NGINX 1M default.

**Closed by ericgaspar** 2021-06-01 13:01 UTC

**Comment by colmoneill** [comment] 2021-06-02 09:51
This is great, thank you very much!
